### ISSUE TITLE
Release a new version supporting Python 3

### ISSUE THREAD

**Issue by nth10sd** [sunpinyin/sunpinyin#107] opened 2020-08-10 18:47 UTC
This will soon be removed [from Gentoo Linux](https://bugs.gentoo.org/695010), please [cut a new release](https://github.com/sunpinyin/sunpinyin/releases) supporting Python 3, which has already landed on master.

**Comment by XVilka** [comment] 2021-03-02 04:41
Probably a duplicate of https://github.com/sunpinyin/sunpinyin/issues/94#issuecomment-781902193

**Comment by tchaikov** [comment] 2021-03-02 05:49
@nth10sd sorry for the latency. just cut a new release, see https://github.com/sunpinyin/sunpinyin/releases/tag/v3.0.0-rc2

**Closed by tchaikov** 2021-03-02 05:50 UTC
